### ISSUE TITLE
environment variables are not copied to template.json

### ISSUE THREAD

**Issue by theburningmonk** [SAPessi/serverless-sam#12]

**Comment by sapessi** [comment]
Can you provide a sample serverless template? I've add an integration test using the [env sample](https://github.com/serverless/examples/blob/master/aws-node-env-variables/serverless.yml) and I see environment variables exported correctly

**Comment by theburningmonk** [comment]
```
service: big-mouth

plugins:
  - serverless-pseudo-parameters
  - serverless-sam

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:scan
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/restaurants
    - Effect: Allow
      Action: execute-api:Invoke
      Resource: arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:*/*/GET/restaurants

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
    environment:
      restaurants_api: xxx
      cognito_user_pool_id: xxx
      cognito_client_id: xxx

  get-restaurants:
    handler: functions/get-restaurants.handler
    events:
      - http:
          path: /restaurants/
          method: get
          authorizer: aws_iam
    environment:
      restaurants_table: restaurants

  search-restaurants:
    handler: functions/search-restaurants.handler
    events:
      - http:
          path: /restaurants/search
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:374852340823:userpool/xxx
    environment:
      restaurants_table: restaurants

resources:
  Resources:
    restaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: restaurants
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
```
