### ISSUE TITLE
Support for multiple API events per function

### ISSUE THREAD

**Issue by TomiTakussaari** [SAPessi/serverless-sam#17]
So i'm trying to create lambda based webapp, that would need to handle all kinds of URLs, based on [serverless-http](https://github.com/dougmoscrop/serverless-http/blob/master/docs/EXAMPLES.md).

serverless.yml would look like this:

```
functions:
  myApp:
    handler: lambda.handler
    events:
      - http:
          path: /{any+}
          method: ANY
      - http:
          path: /
          method: ANY
```
But this fails with error "Resource MyAppLambdaPermission already exists" when using serverless-sam.

I guess it should create permission only once per function in [here](https://github.com/SAPessi/serverless-sam/blob/1f37af24a3e86040726a654ddcc3c62f6945eed1/lib/FunctionConverter.js#L112) ?
