### ISSUE TITLE
Individual package artifacts are ignored

### ISSUE THREAD

**Issue by byteSamurai** [SAPessi/serverless-sam#26]
For small projects a global artifact is used:

```
package:
  artifact: path/to/artifact.zip
```
but in later projects we used to separate the functions to reduce upload size and isolate dependencies:

```
package:
  individually: true

functions:
  tagGenerator:
    handler: hakuna.matata.Handler
    package:
      artifact: path/to/artifact-for-function.zip
```

This is valid using serverless framework, but the plugin ignores the artifacts per function. so the are missing in the generated sam template.
